### ISSUE TITLE
Danis-Import csv Inhalt und Format

### ISSUE THREAD

**Issue by chrismuella** [diplomify/documentation#7]
Könntetst du mir aufschreiben, welche Spalten beim csv import vorhanden sein MÜSSEN?
Und welches Format die csv haben muss?

Dann kann ich dazu in in der Docu einen Artikel schreiben "Import aus Danis vorbereiten"

**Comment by chrismuella** [comment]
Ich habe jetzt unter Tabellen anagelegt, in denen man nachschauen kann, welche Merkmale über ein bestimmtes Verfahren importiert werden können.
Könntest du da mal drübergucken und ggf. ergänzen oder korrigieren?

**Comment by michip** [comment]
Die Tabelle erste sieht soweit gut aus. Bei der zweiten muss noch "Email" ergänzt werden. Außerdem könnte man noch die Benutzer ID, Klassen ID usw. dazu schreiben. Bei Webuntis würde ich jedoch bei "Geburtsort" `nicht verfügbar` oder so schreiben. Folgende Spalten nutze ich beim Import von Schülern:

```
STUDENT_COLUMN_MATCHES = {
        "SchuelerNachname": "last_name",
        "SchuelerRufname": "first_name",
        "SchuelerGeburtsdatum": "date_of_birth",
        "SchuelerGeburtsort": "birth_place",
        "SchuelerAufnahmedatum": "school_entered_at",
        "SchuelerGeschlecht": "gender",
        "SchuelerId": "student_id"
    }

    CLASS_COLUMN_MATCHES = {
        "GruppeBezeichnung": "identifier",
        "GruppeId": "class_id"
    }
```

Bei den Lehrern sind es hingegen bislang diese Spalten
```
USER_COLUMN_MATCHES = {
        "Nachname": "last_name",
        "Vorname": "first_name",
        "Import-ID": "external_identifier",
        "E-Mail-Adresse": "email",
        "Account": "username"
    }
```

**Comment by chrismuella** [comment]
Den Username der Lehrer holst du aus csv und WebUntis?

**Comment by chrismuella** [comment]
CLASS_COLUMN_MATCHES - sind das auch die Kurse oder nur die Klassen?

**Comment by michip** [comment]
> CLASS_COLUMN_MATCHES - sind das auch die Kurse oder nur die Klassen?

Das sind nur die Klassen. Den Unterricht muss man selbst zuordnen.

> Den Username der Lehrer holst du aus csv und WebUntis?

Ja genau. Momentan ist der Import per csv jedoch wegen der Umstellung auf die neuen externen Identifier abgetellt.
